# Generated by Django 4.1.5 on 2023-01-31 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_managers_alter_post_slug'),
        ('blog', '0005_alter_post_managers'),
    ]

    operations = [
    ]
